WIP Feature/issue 490 update bc211 database
pg-irc/pathways-backend pull request #505
Opened 2020-02-07 18:20 UTC by rasmus-storjohann-PG

2020-10-05 17:22 UTC, ian-lin-PG commented on bc211/tests/test_updater.py
> +              with_phone_numbers([new_phone_at_location]).
Would like to see at test with multiple phone numbers for replacement.

2020-10-06 20:45 UTC, tomy-pg commented on bc211/location.py
> +        LOGGER.info('delete "%2"', i)
I am seeing a logging error during import related to this I believe. Do you mean to use `"%s"` here?

2020-10-06 22:20 UTC, rasmus-storjohann-PG commented
There are definitely benefits to using CSV as the source of truth, including being able to keep it in git. Found some reads on this [here](https://www3.dbmaestro.com/blog/how-the-database-is-your-main-agile-development-bottleneck) and [here](https://www3.dbmaestro.com/blog/using-git-for-database-why-and-how).

2020-10-07 22:42 UTC, tomy-pg requested changes

2020-10-07 22:42 UTC, tomy-pg commented on bc211/location.py
>              LOGGER.info('created "%s" "%s"', location.id, location.name)
I do not think we need to log when an organization, location or a service is created anymore if we are importing data after flushing the current data in the database.

2020-10-08 18:18 UTC, merged