Feature/issue 557 import bc211 csv
pg-irc/pathways-backend pull request #565
Opened 2020-10-14 20:53 UTC by rasmus-storjohann-PG

2020-10-26 22:59 UTC, rasmus-storjohann-PG commented
Add test to cover unicode characters.

2020-10-26 23:20 UTC, tomy-pg requested changes

2020-10-26 23:20 UTC, tomy-pg commented on bc211/csv_import/parser.py
> +    return [build_taxonomy_object(name, vocabulary) for name in names if name]
From QA @ian-lin-PG and I are seeing in the taxonomy `name` column that taxonomies that should be together are separated into different rows. 
See screenshot below. 
<img width="684" alt="Screen Shot 2020-10-26 at 4 17 40 PM" src="https://user-images.githubusercontent.com/47794846/97238637-18eb8e80-17a7-11eb-9486-8536874608c0.png">

2020-11-09 18:41 UTC, tomy-pg commented on bc211/csv_import/parser.py
> +            organization_or_service[output_header] = fix_date_time_string(value)
If the `last_verified_on` is empty, shouldn't we return empty as opposed to returning the date of when the script was run?

2020-11-09 18:50 UTC, ian-lin-PG commented on bc211/csv_import/parser.py
> +            organization_or_service['id'] = str(uuid.uuid4())
I don't think we should generated service or organization ids given that BC211 are responsible for creating the ids. I think a better approach is to log the services/organizations without ids and forward them to BC211. As @tomy-pg pointed out, if a bookmarked service has its id changed we can dealing with complication down the road.

2020-11-09 19:06 UTC, tomy-pg commented on bc211/csv_import/parser.py
> +                                                         organization_or_service['alternate_name'])
I like this solution better, but we can run into errors if bc211 eventually adds an id to the organization / service and a user has one of these bookmarked on their app. It may be that we want to log out then report these organizations and services that have missing ids to bc211 before we add them to the processed csv.

2020-11-09 19:16 UTC, tomy-pg commented on bc211/csv_import/parser.py
> +        return None
Oh nice. Omit previous comment on this.

2020-11-09 19:52 UTC, rasmus-storjohann-PG commented on bc211/csv_import/parser.py
> +        return None
Should rename the function to make this not surprising

2020-11-09 19:59 UTC, rasmus-storjohann-PG commented on bc211/management/commands/import_bc211_csv_data.py
> +import argparse
rename to `convert_bc211_csv_to_openreferral_csv`

2020-11-09 20:00 UTC, rasmus-storjohann-PG commented on bc211/csv_import/parser.py
> +                                                     organization_or_service['alternate_name'])
Terminate with an error on this condition

2020-12-14 19:09 UTC, tomy-pg requested changes

2020-12-14 19:09 UTC, tomy-pg commented on bc211/csv_import/parser.py
> +            phone_numbers[phone_index]['type'] = 'Fax'
The `phones.csv` generated only contains phone types that are `Fax`. The rest of the rows do not contain a type. 

Looking at the iCarol.csv: `PhoneType1` does not seem to have any values inside of its cells. For this, we could possibly do something like:

```
if header == PhoneType1:
     phone_numbers[phone_index]['type'] = 'PhoneNumber1' # or Phone1, Primary phone
```

2020-12-17 18:28 UTC, tomy-pg approved these changes

2020-12-17 18:30 UTC, merged