WIP: Feature/issue 564 import open referral csv
pg-irc/pathways-backend pull request #573
Opened 2020-11-17 00:33 UTC by tomy-pg

2020-11-17 23:37 UTC, rasmus-storjohann-PG requested changes

2020-11-17 23:37 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/parser.py
> +    return remove_double_escaped_html_markup(service_id)
In those cases where these functions are identical in terms of their behaviour, I think you'll find that combining them and naming them to reflect what they do (parse_required_field_with_double_escaped_html()) will make the code at the calling site more readable.

2020-11-20 18:13 UTC, tomy-pg commented on bc211/open_referral_csv_import/is_inactive.py
> +    return description and description.strip().startswith('DEL')
I have refactored `is_inactive` to work with both xml and open referral csv files. While importing the open referral csv files, I noticed some inactive records were not `DEL` but varied in casing such as `Del` so I made this case insensitive.

2020-11-20 18:20 UTC, tomy-pg commented on bc211/open_referral_csv_import/is_inactive.py
> +    return description and description.strip().startswith('DEL')
I noticed most inactive records also included a number directly after `DEL`, `DEL16`.
In one case, I also noticed an inactive record that contained a whitespace character between DEL and a number, `DEL 16`. I have included these cases in the function to improve it and also make it less susceptible to errors since I make the `DEL` look-up case insensitive.

2020-11-20 18:40 UTC, tomy-pg commented on bc211/open_referral_csv_import/service_taxonomy.py
> +    save_service_taxonomy_term(service_id, taxonomy_id)
The TaxonomyTerm model services_taxonomy_terms is built from does not have the `id` column defined so Django creates the id for us. Let me know if you want this behaviour to change.

2020-11-20 18:43 UTC, tomy-pg commented on bc211/open_referral_csv_import/address.py
> +    return active_record
The `Address` model that we use does not have the `id` column defined so Django auto-generates the id for us. I recognize in your work you generate an id as well. Do you want me to change this or leave the model as is?

I will make the change to handle all `address_x` fields.

2020-11-20 22:44 UTC, tomy-pg commented on bc211/open_referral_csv_import/parser.py
> +    return remove_double_escaped_html_markup(service_id)
Are you suggesting that instead of:
`active_record.organization_id = parse_organize_id(...)`
`active_record.name = parse_name(...)`
to do:
`active_record.organization_id = parse_required_field_with_double_escaped_html(...)`
`active_record.name = parse_required_field_with_double_escaped_html(...)`
?

2020-11-24 00:31 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/address.py
> +    return active_record
Change it so that it uses the ids I generate in my PR. It's so that repeated imports of the same data will give consistent ids each time.

2020-12-02 18:49 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_sandbox.py
> +        LocationAddress(address=self.address_3, location=self.location_3, address_type=self.physical_address_type).save()
I would have thought that this would work
```py
LocationAddress(address=self.address_3, location=self.location_3, address_type='physical_address').save()
```

2020-12-08 00:23 UTC, rasmus-storjohann-PG requested changes

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/phone.py
> +    return active_record
The naming convention is that "build" means make the AR instance, and "create" means make the AR and save it to the DB. So you might want to include the "save" step in the helper function and rename it to "create_..."

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/service_at_location.py
> +def service_at_location_has_invalid_data(row, collector):
Inconsistent naming, inactive, not invalid

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on human_services/locations/models.py
> +        alternate_name=models.CharField(blank=True, max_length=200),
Django's handling of fields where blank and null are different is messy, so we want to consistently set both to true or both to false. I also don't want to remember what their values default to, so they should always both be given regardless.

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on human_services/addresses/tests/test_models.py
> +        self.assertTrue(Address.objects.first().city is None)
nice

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on bc211/tests/test_importer.py
> +        inactive_description = 'DEL17 ' + a_string()
What is the significance of the two digits? What is the expected behaviour if the description starts with 'DEL78'? I don't think the digits mean anything, in which case they should not appear in the test.

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on bc211/service.py
> +    if is_inactive(service.description):
I like the old way better, because the fact that the description field is where the DEL is found is delegated to the helper function ... with the new code, the higher level code needs to include that detail, which is not as clean for separation of concerns. But if you have good reason for this change, I'm open to it.

2020-12-08 00:23 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_parser.py
> +        self.assertEqual(f'{address_1}\n{address_2}', parsed_addresses)
nice

2020-12-08 22:27 UTC, tomy-pg commented on bc211/is_inactive.py
> +    return re.search(r'^[D-d-E-e-L-l]{3}[0-9\s]', stripped_description)
There is already a test case that exists which ensure we don't accidentally mark strings starting with "Del..." as inactive.

2020-12-10 01:24 UTC, tomy-pg commented on bc211/open_referral_csv_import/address.py
> +        pass
These will be handled or removed once your PR is in. I have these here temporarily to be able to test the script.

2020-12-10 01:30 UTC, tomy-pg commented on bc211/service.py
> +    if is_inactive(service.description):
Previously we were building active records, then checking to see if the record is inactive.

I made this change so that I could first parse the description, see if BC211 marked the record as inactive and then build the record. 

I am open to changing this back if you would like.

2020-12-10 01:37 UTC, tomy-pg commented on bc211/open_referral_csv_import/service_taxonomy.py
> +        Service.objects.bulk_update(taxonomy_updates_for_service)
I am using `bulk_update ` here as opposed to `bulk_create` because the `ServiceTaxonomyTerm` intermediary table is not explicitly declared. Therefore, I cannot use the ORM to do something like ServiceTaxonomyTerm.objects.bulk_create()
We seem to create the table like so:
```
/human_services/services/models
class Service():
    id = ...
    organization = ...
    taxonomy_terms = models.ManyToManyField(TaxonomyTerm,
                                            db_table='services_service_taxonomy_terms')
```
As part of this PR, I can create the ServiceTaxonomyTerm model explicitly. What are your thoughts on this @rasmus-storjohann-PG ?

2020-12-10 23:00 UTC, tomy-pg commented on bc211/open_referral_csv_import/tests/test_sandbox.py
> +        LocationAddress(address=self.address_3, location=self.location_3, address_type=self.physical_address_type).save()
`address_type` expects an `AddressType` instance

2020-12-10 23:08 UTC, rasmus-storjohann-PG requested changes

2020-12-14 22:38 UTC, rasmus-storjohann-PG requested changes

2020-12-14 22:38 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_importer.py
> +        self.assertEqual(locations[0].point.y, float(the_latitude))
Conversion from float to string always succeeds, conversion from string to float can fail. So when you have the choice, it's better to use the float -> string form. Here you could have done `the_latitude = a_latitude()`, `with_latitude(str(the_latitude))` and `self.assertEqual(locations[0].point.x, the_longitude)`

2020-12-14 22:38 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_importer.py
> +class OpenReferralAddressImporterTests(TestCase):
You can drop the `OpenReferral` prefix here, you hare not using it consistently and it hurts readability

2020-12-14 22:38 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_importer.py
> +        the_country = a_string(2, string.ascii_uppercase)
See the established pattern for `a_website_address()` and `an_email_address()`, you should create `a_country_code()`.

2020-12-14 22:38 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_importer.py
> +                            with_address_2(the_address_2).
You need to test all four fields, this is a typical area where bugs can hide for a long time, since most addresses don't use all four lines.

2020-12-14 22:38 UTC, rasmus-storjohann-PG commented on bc211/open_referral_csv_import/tests/test_importer.py
> +        self.assertEqual(phone_number_types[0].id, the_phone_type)
I don't see why this is its own test suite, can be combined with the test suite below

2020-12-14 22:57 UTC, rasmus-storjohann-PG commented
OK, so I've read through the tests and they look good, see a few comments above. Some functions that are complicated enough that they should have tests: `service_taxonomy#read_and_import_rows()`,

2020-12-14 23:06 UTC, rasmus-storjohann-PG requested changes

2020-12-15 17:31 UTC, tomy-pg commented on human_services/locations/models.py
> -        unique_together = ('location', 'address_type')
From our discussion, we noticed that there are seemingly repeated rows of the same location and address type. I have since brought this `unique_together` constraint and will log out the validation errors with information of the row violating it.

2020-12-17 18:33 UTC, closed without merging