Feature/issue 615 include mb data in import scripts
pg-irc/pathways-backend pull request #621
Opened 2021-03-19 20:28 UTC by rasmus-storjohann-PG

2021-03-22 16:23 UTC, rasmus-storjohann-PG commented on newcomers_guide/management/commands/import_newcomers_guide.py
> +# add bc or mb prefix to topic ids
remove

2021-03-22 16:23 UTC, rasmus-storjohann-PG commented on newcomers_guide/management/commands/generate_client_fixtures.py
> +# add region taxonomy term to each topic
remove

2021-03-22 16:27 UTC, rasmus-storjohann-PG commented on utility/prepare_deploy.sh
> +importICarolCsvServiceData ../content/organizationAsServices.csv "${OutputDir}/openreferral/organizationsAsService" bc
Add `_bc` suffix to primary keys

2021-03-22 17:42 UTC, tomy-pg approved these changes
Looks good to me

2021-03-22 17:42 UTC, tomy-pg commented on utility/prepare_deploy.sh
> +importICarolCsvServiceData $BC211Path ./open_referral_csv_files bc
Nice. The helper makes it much easier to understand what is going on

2021-03-22 21:08 UTC, tomy-pg requested changes

2021-03-22 21:08 UTC, tomy-pg commented on utility/prepare_deploy.sh
> +    if [ "$manitobaWinPath" != "" ] && [! -f $manitobaWinPath ]
missing space after square bracket causes this error:
`./utility/prepare_deploy.sh: line 117: [!: command not found`

The script still runs but crashes before any WIN data can be processed.

Change to:
`if [ "$manitobaWinPath" != "" ] && [ ! -f $manitobaWinPath ]`

2021-03-25 16:35 UTC, rasmus-storjohann-PG commented on newcomers_guide/management/commands/import_newcomers_guide.py
> +# add bc or mb prefix to topic ids
done

2021-03-25 16:35 UTC, rasmus-storjohann-PG commented on newcomers_guide/management/commands/generate_client_fixtures.py
> +# add region taxonomy term to each topic
done

2021-03-25 16:36 UTC, rasmus-storjohann-PG commented on utility/prepare_deploy.sh
> +    if [ "$manitobaWinPath" != "" ] && [! -f $manitobaWinPath ]
thanks, fixed

2021-03-25 16:39 UTC, rasmus-storjohann-PG commented on utility/prepare_deploy.sh
> +importICarolCsvServiceData ../content/organizationAsServices.csv "${OutputDir}/openreferral/organizationsAsService" bc
No change needed, brain fart on my part

2021-03-25 22:16 UTC, merged